services:
  mahi-dashboard:
    build:
      context: ./mahi-dashboard
    container_name: mahi-dashboard
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost:3000
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 120s
    labels:
      - traefik.enable=true
      # Service
      - traefik.http.services.emma.loadbalancer.server.port=3145
      # Router
      - traefik.http.routers.emma.rule=Host(`emma.ugentsailing.be`)
      - traefik.http.routers.emma.service=emma
      - traefik.http.routers.emma.entrypoints=https
      - traefik.http.routers.emma.tls=true
      - traefik.http.routers.emma.tls.certresolver=letsencrypt
    networks:
      - traefik_proxy

  manet:
    build:
      context: .
      dockerfile: manet.Dockerfile
    container_name: manet
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - ./manet:/app/manet
      - ./manet.conf:/app/manet.conf

networks:
  traefik_proxy:
    external: true